"""Orchestrator — wires triage, resolution, and escalation into one pipeline.

This is deliberately a fourth file, not a merge of the other three into one
blob. Each agent stays independently testable; this is just the coordination
layer that calls them in the right order and passes state between them.

Per-turn flow:
  no active ticket for this user
    -> TriageAgent.classify (chitchat + taxonomy, one call)
       -> pure chitchat: canned response, no ticket created
       -> needs_clarification: stub clarifying question (see TODO below)
       -> classified: look up its StepSequence, start a TicketState,
          hand the same message straight to ResolutionAgent (it may
          already contain the first slot's value)
  active ticket for this user
    -> hand the message straight to ResolutionAgent.process_turn
       (no re-triage -- the ticket is already on a known sequence;
       slot extraction handles "hi" gracefully by just re-asking)

Then, whatever ResolutionAgent.process_turn returns:
    ASK_CUSTOMER / INFORM_CUSTOMER -> reply, keep ticket active
    COMPLETED                      -> reply, drop ticket
    HANDOFF_APPROVAL               -> reply, drop ticket (see TODO)
    HANDOFF_ESCALATION             -> EscalationAgent.handle, reply, drop ticket

Explicitly NOT included yet (matches decisions made earlier in this build):
  - Guardrail/injection checks and emotion scoring. Both were scoped as
    upstream-of-everything, per-turn concerns -- add them as steps before
    the triage call once built, not inside this file's branching.
  - Human-approval resumption. HANDOFF_APPROVAL currently just ends the
    ticket with a message; there's no "approved -> resume sequence" path
    yet (same gap flagged on resolution_agent.py earlier).
  - Real ticket persistence / dedup. `_active_tickets` is an in-memory
    dict keyed by user_id, for one process, for testing. A real deployment
    needs this backed by a DB/session store, and the open-ticket dedup
    check discussed earlier in this project isn't implemented here.
  - Clarifying-question phrasing when triage sets needs_clarification=True
    currently returns a generic stub sentence -- build a proper narrow
    phrasing call for this later, same pattern as resolution_agent's
    _phrase().
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

from src.llm_providers import GenerationClient
from src.agents.triage_agent import TriageAgent
from src.agents.resolution_agent import (
    BackendFunctionRegistry,
    OutcomeType,
    ResolutionAgent,
    ResolutionOutcome,
    StepSequence,
    TicketState,
)
from src.agents.escalation_agent import EscalationAgent
from src.agents.resolution_functions import FUNCTIONS
from src.agents.sequence_loader import get_sequence, SequenceNotFoundError


# ---------------------------------------------------------------------------
# The sequence loader is the only source of resolution steps. It resolves the
# flow/subflow returned by triage against data/sequence_table_autogenerated.json.


# ---------------------------------------------------------------------------
# Turn result — what the orchestrator hands back to whatever's calling it
# (an API route, a chat UI, a test harness).
# ---------------------------------------------------------------------------

@dataclass
class TurnResult:
    message: str
    ticket_id: Optional[str]
    finished: bool  # True if no ticket is active after this turn
    messages: list[str] = field(default_factory=list)


class Orchestrator:
    def __init__(
        self,
        llm: GenerationClient,
        *,
        functions: Optional[BackendFunctionRegistry] = None,
        escalation_queue=None,
    ) -> None:
        self.triage = TriageAgent(llm)
        self.resolution = ResolutionAgent(llm, functions or BackendFunctionRegistry(FUNCTIONS))
        self.escalation = EscalationAgent(llm, queue=escalation_queue)

        # user_id -> (TicketState, StepSequence). In-memory, single-process,
        # for testing only -- see module docstring TODO.
        self._active_tickets: dict[str, tuple[TicketState, StepSequence]] = {}

    async def handle_message(self, user_id: str, message: str) -> TurnResult:
        active = self._active_tickets.get(user_id)

        if active is not None:
            state, sequence = active
            outcome = await self.resolution.process_turn(state, sequence, customer_message=message)
            return await self._handle_outcome(user_id, sequence, outcome)

        triage_result = await self.triage.classify(message)

        if not triage_result.has_actionable_request:
            message = triage_result.canned_response()
            return TurnResult(message=message, ticket_id=None, finished=True, messages=[message])

        if triage_result.needs_clarification or triage_result.flow is None or triage_result.subflow is None:
            # TODO: replace with a proper narrow phrasing call, same pattern
            # as resolution_agent's _phrase(), once built.
            return TurnResult(
                message="Could you tell me a bit more about what you need help with?",
                ticket_id=None,
                finished=True,
                messages=["Could you tell me a bit more about what you need help with?"],
            )

        try:
            sequence = get_sequence(triage_result.flow, triage_result.subflow)
        except SequenceNotFoundError:
            return TurnResult(
                message="I need a person to help with that one -- I'm passing this along.",
                ticket_id=None,
                finished=True,
                messages=["I need a person to help with that one -- I'm passing this along."],
            )

        state = TicketState.start(flow=triage_result.flow, subflow=triage_result.subflow, sequence=sequence)
        self._active_tickets[user_id] = (state, sequence)

        # Same original message -- it may already contain the first slot's
        # value (e.g. "cancel order 4471" already has order_id).
        outcome = await self.resolution.process_turn(state, sequence, customer_message=message)
        return await self._handle_outcome(user_id, sequence, outcome)

    async def _handle_outcome(
        self, user_id: str, sequence: StepSequence, outcome: ResolutionOutcome
    ) -> TurnResult:
        state = outcome.state

        if outcome.outcome_type in (OutcomeType.ASK_CUSTOMER, OutcomeType.INFORM_CUSTOMER):
            self._active_tickets[user_id] = (state, sequence)
            messages = outcome.messages or ([outcome.message] if outcome.message else [])
            return TurnResult(
                message=outcome.message or "",
                ticket_id=state.correlation_id,
                finished=False,
                messages=messages,
            )

        if outcome.outcome_type == OutcomeType.COMPLETED:
            self._active_tickets.pop(user_id, None)
            message = outcome.message or "All set!"
            return TurnResult(
                message=message,
                ticket_id=state.correlation_id,
                finished=True,
                messages=outcome.messages or [message],
            )

        if outcome.outcome_type == OutcomeType.HANDOFF_APPROVAL:
            # No resumption path yet -- see module docstring TODO.
            self._active_tickets.pop(user_id, None)
            message = outcome.message or "This needs a bit more review."
            return TurnResult(message=message, ticket_id=state.correlation_id, finished=True, messages=[message])

        if outcome.outcome_type == OutcomeType.HANDOFF_ESCALATION:
            self._active_tickets.pop(user_id, None)
            _payload, message = await self.escalation.handle(state, outcome, emotion=None)
            return TurnResult(
                message=message, ticket_id=state.correlation_id, finished=True, messages=[message]
            )

        raise ValueError(f"Unhandled outcome type {outcome.outcome_type!r}")


__all__ = ["Orchestrator", "TurnResult"]


# ---------------------------------------------------------------------------
# Example usage
# ---------------------------------------------------------------------------

async def _example():
    from src.llm_providers import ProviderFactory, Provider

    llm = ProviderFactory.create(Provider.GEMINI, model="gemini-2.0-flash")
    orchestrator = Orchestrator(llm)

    for msg in ["hi", "I want to cancel my order", "it's order 4471"]:
        result = await orchestrator.handle_message(user_id="user_1", message=msg)
        print(f"{msg!r} -> {result.message!r} (finished={result.finished})")


if __name__ == "__main__":
    import asyncio
    asyncio.run(_example())
