"""Load resolution sequences selected by the triage agent.

``sequence_table_autogenerated.json`` is a linear, first-pass table.  It has
no branch destinations or slot metadata, so this module deliberately does not
invent them.  It converts the rows it can represent safely:

* ``response`` rows become :class:`ResponseStep` instances;
* ``slot`` rows request one customer-provided value; and
* ``action`` and ``check`` rows invoke their named backend function in order.

When a flow later needs conditional branching, replace that row with a refined
sequence definition rather than guessing a branch here.
"""

from __future__ import annotations

import json
import re
from functools import lru_cache
from pathlib import Path
from typing import Any, Optional

from src.agents.resolution_agent import (
    ActionStep,
    ResponseStep,
    SlotSource,
    SlotStep,
    Step,
    StepSequence,
)


DEFAULT_SEQUENCE_TABLE_PATH = (
    Path(__file__).resolve().parents[1] / "data" / "sequence_table_autogenerated.json"
)


class SequenceNotFoundError(LookupError):
    """Raised when triage selects a flow/subflow absent from the table."""


def _step_id(index: int, label: str) -> str:
    normalized = re.sub(r"[^a-z0-9]+", "_", label.lower()).strip("_") or "step"
    return f"step_{index}_{normalized}"


def _slot_name(label: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", label.lower()).strip("_") or "customer_detail"


def _build_sequence(row: dict[str, Any]) -> StepSequence:
    flow = row["flow"]
    subflow = row["subflow"]
    raw_steps = row.get("steps")
    if not isinstance(raw_steps, list) or not raw_steps:
        raise ValueError(f"Sequence {flow!r} / {subflow!r} has no steps")

    steps: dict[str, Step] = {}
    for index, raw_step in enumerate(raw_steps, start=1):
        raw_type = raw_step.get("step_type")
        label = raw_step.get("label")
        instruction = raw_step.get("instruction")
        if not all(isinstance(value, str) and value for value in (raw_type, label, instruction)):
            raise ValueError(f"Invalid step {index} in {flow!r} / {subflow!r}")

        step_id = _step_id(index, label)
        next_step_id = _step_id(index + 1, raw_steps[index]["label"]) if index < len(raw_steps) else None

        if raw_type == "response":
            step: Step = ResponseStep(
                step_id=step_id, instruction=instruction, next_step_id=next_step_id
            )
        elif raw_type == "slot":
            step = SlotStep(
                step_id=step_id,
                instruction=instruction,
                slot_name=_slot_name(label),
                source=SlotSource.CUSTOMER_PROVIDED,
                next_step_id=next_step_id,
            )
        elif raw_type in {"action", "check"}:
            # The source table has no check condition or true/false targets.
            # Its named backend operation is still useful, so execute it
            # linearly rather than fabricating a branch.
            step = ActionStep(
                step_id=step_id,
                instruction=instruction,
                function_name=label,
                next_step_id=next_step_id,
            )
        else:
            raise ValueError(f"Unknown step type {raw_type!r} in {flow!r} / {subflow!r}")
        steps[step_id] = step

    return StepSequence(
        flow=flow,
        subflow=subflow,
        start_step_id=_step_id(1, raw_steps[0]["label"]),
        steps=steps,
    )


@lru_cache(maxsize=4)
def load_sequence_table(path: str = str(DEFAULT_SEQUENCE_TABLE_PATH)) -> dict[tuple[str, str], StepSequence]:
    """Read the table once and index its sequences by ``(flow, subflow)``."""
    table_path = Path(path)
    try:
        rows = json.loads(table_path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise FileNotFoundError(f"Sequence table does not exist: {table_path}") from exc
    except json.JSONDecodeError as exc:
        raise ValueError(f"Sequence table is not valid JSON: {table_path}") from exc

    if not isinstance(rows, list):
        raise ValueError("Sequence table must contain a JSON list")

    sequences: dict[tuple[str, str], StepSequence] = {}
    for row in rows:
        if not isinstance(row, dict):
            raise ValueError("Each sequence-table entry must be a JSON object")
        sequence = _build_sequence(row)
        key = (sequence.flow, sequence.subflow)
        if key in sequences:
            raise ValueError(f"Duplicate sequence for {sequence.flow!r} / {sequence.subflow!r}")
        sequences[key] = sequence
    return sequences


def get_sequence(flow: str, subflow: str, *, path: Optional[str] = None) -> StepSequence:
    """Return the steps matching a triage result, or raise a clear lookup error."""
    sequences = load_sequence_table(path or str(DEFAULT_SEQUENCE_TABLE_PATH))
    try:
        return sequences[(flow, subflow)]
    except KeyError as exc:
        raise SequenceNotFoundError(
            f"No sequence found for flow={flow!r}, subflow={subflow!r}"
        ) from exc


__all__ = [
    "DEFAULT_SEQUENCE_TABLE_PATH",
    "SequenceNotFoundError",
    "load_sequence_table",
    "get_sequence",
]
